// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userServices

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	EmailNormalized     sql.NullString `json:"email_normalized"`
	PasswordHash        string         `json:"-"`
	PasswordChangedAt   time.Time      `json:"password_changed_at"`
	Name                string         `json:"name"`
	DateOfBirth         sql.NullTime   `json:"date_of_birth"`
	Phone               sql.NullString `json:"phone"`
	VerifiedEmail       bool           `json:"verified_email"`
	IsActive            bool           `json:"-"`
	Onboarded           bool           `json:"onboarded"`
	DeactivatedAt       sql.NullTime   `json:"deactivated_at"`
	CreatedAt           time.Time      `json:"-"`
	UpdatedAt           time.Time      `json:"-"`
	Version             int32          `json:"version"`
	LastLoginAt         sql.NullTime   `json:"-"`
	FailedLoginAttempts int32          `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime   `json:"-"`
}
